In [8]:
 customer={
    "first_name" :"Muhammad",
    "middle_name" :"Mudassir",
    "last_name" :"Raza",
    "address" : "A-120  gulberg block 20",
    "number" : "0313333990",
    1  : "loving"
}
print(customer)
print(customer["first_name"])
print(customer["middle_name"])
print(customer["last_name"])
print(customer["address"])
print(customer["number"])
print(customer[1])

{'first_name': 'Muhammad', 'middle_name': 'Mudassir', 'last_name': 'Raza', 'address': 'A-120  gulberg block 20', 'number': '0313333990', 1: 'loving'}
Muhammad
Mudassir
Raza
A-120  gulberg block 20
0313333990
loving

In [9]:
#10 students
# 2 classes
# 4 exam
# 3 attempts allow
# take student name and exam_name as input and show in which class the student get maximum

students=[]

class_1={
    "name":"AI",
    "marks":{
        "quiz1":40,
        "quiz2":45,
        "mid":50,
        "final":55
         
    }
    
    
}

class_2={
    "name":"CNC",
    "marks":{
        "quiz1":42,
        "quiz2":44,
        "mid":53,
        "final":59
         
    }
    
    
}
student_1001 ={
    "name":"arif",
    "class_AI":class_1,
    "class_CNC":class_2,
    
}
students.append(student_1001)
print(students)

[{'name': 'arif', 'class_AI': {'name': 'AI', 'marks': {'quiz1': 40, 'quiz2': 45, 'mid': 50, 'final': 55}}, 'class_CNC': {'name': 'CNC', 'marks': {'quiz1': 42, 'quiz2': 44, 'mid': 53, 'final': 59}}}]

In [10]:

class_1={
    "name":"AI",
    "marks":{
        "quiz1":41,
        "quiz2":48,
        "mid":77,
        "final":55
         
    }
    
    
}

class_2={
    "name":"CNC",
    "marks":{
        "quiz1":49,
        "quiz2":44,
        "mid":51,
        "final":56
         
    }
    
    
}
student_1002 ={
    "name":"ali",
    "class_AI":class_1,
    "class_CNC":class_2,
    
}
students.append(student_1002)
print(students)

[{'name': 'arif', 'class_AI': {'name': 'AI', 'marks': {'quiz1': 40, 'quiz2': 45, 'mid': 50, 'final': 55}}, 'class_CNC': {'name': 'CNC', 'marks': {'quiz1': 42, 'quiz2': 44, 'mid': 53, 'final': 59}}}, {'name': 'ali', 'class_AI': {'name': 'AI', 'marks': {'quiz1': 41, 'quiz2': 48, 'mid': 77, 'final': 55}}, 'class_CNC': {'name': 'CNC', 'marks': {'quiz1': 49, 'quiz2': 44, 'mid': 51, 'final': 56}}}]

In [11]:

class_1={
    "name":"AI",
    "marks":{
        "quiz1":51,
        "quiz2":10,
        "mid":12,
        "final":33
         
    }
    
    
}

class_2={
    "name":"CNC",
    "marks":{
        "quiz1":33,
        "quiz2":99,
        "mid":100,
        "final":88
         
    }
    
    
}
student_1003 ={
    "name":"raza",
    "class_AI":class_1,
    "class_CNC":class_2,
    
}
students.append(student_1003)
# print(students)

In [12]:

class_1={
    "name":"AI",
    "marks":{
        "quiz1":41,
        "quiz2":66,
        "mid":67,
        "final":35
         
    }
    
    
}

class_2={
    "name":"CNC",
    "marks":{
        "quiz1":40,
        "quiz2":5,
        "mid":68,
        "final":77
         
    }
    
    
}
student_1004 ={
    "name":"hassan",
    "class_AI":class_1,
    "class_CNC":class_2,
    
}
students.append(student_1004)
# print(students)

In [13]:

class_1={
    "name":"AI",
    "marks":{
        "quiz1":41,
        "quiz2":48,
        "mid":50,
        "final":52
         
    }
    
    
}

class_2={
    "name":"CNC",
    "marks":{
        "quiz1":40,
        "quiz2":60,
        "mid":76,
        "final":55
         
    }
    
    
}
student_1005 ={
    "name":"faizan",
    "class_AI":class_1,
    "class_CNC":class_2,
    
}
students.append(student_1005)

In [14]:

class_1={
    "name":"AI",
    "marks":{
        "quiz1":34
        "quiz2":94,
        "mid":93,
        "final":57
         
    }
    
    
}

class_2={
    "name":"CNC",
    "marks":{
        "quiz1":76,
        "quiz2":45,
        "mid":50,
        "final":94
         
    }
    
    
}
student_1006 ={
    "name":"ashtar",
    "class_AI":class_1,
    "class_CNC":class_2,
    
}
students.append(student_1006)

SyntaxError: invalid syntax (1461742794.py, line 5)

In [15]:

class_1={
    "name":"AI",
    "marks":{
        "quiz1":41,
        "quiz2":78,
        "mid":65,
        "final":69
         
    }
    
    
}

class_2={
    "name":"CNC",
    "marks":{
        "quiz1":75,
        "quiz2":74,
        "mid":73,
        "final":77
         
    }
    
    
}
student_1007 ={
    "name":"zehra",
    "class_AI":class_1,
    "class_CNC":class_2,
    
}
students.append(student_1007)

In [16]:

class_1={
    "name":"AI",
    "marks":{
        "quiz1":99,
        "quiz2":88,
        "mid":60,
        "final":51
         
    }
    
    
}

class_2={
    "name":"CNC",
    "marks":{
        "quiz1":51,
        "quiz2":53,
        "mid":44,
        "final":42
         
    }
    
    
}
student_1008 ={
    "name":"yawar",
    "class_AI":class_1,
    "class_CNC":class_2,
    
}
students.append(student_1008)

In [17]:

class_1={
    "name":"AI",
    "marks":{
        "quiz1":39,
        "quiz2":84,
        "mid":89,
        "final":23
         
    }
    
    
}

class_2={
    "name":"CNC",
    "marks":{
        "quiz1":46,
        "quiz2":47,
        "mid":98,
        "final":58
         
    }
    
    
}
student_1009 ={
    "name":"zakir",
    "class_AI":class_1,
    "class_CNC":class_2,
    
}
students.append(student_1009)

In [18]:

class_1={
    "name":"AI",
    "marks":{
        "quiz1":48,
        "quiz2":89,
        "mid":97,
        "final":10
         
    }
    
    
}

class_2={
    "name":"CNC",
    "marks":{
        "quiz1":90,
        "quiz2":25,
        "mid":20,
        "final":30
         
    }
    
    
}
student_10010 ={
    "name":"meesam",
    "class_AI":class_1,
    "class_CNC":class_2,
    
}
students.append(student_10010)

In [19]:
i=0
for student in students:
    print("student : ",i,student,"\n")
    i=i+1

student :  0 {'name': 'arif', 'class_AI': {'name': 'AI', 'marks': {'quiz1': 40, 'quiz2': 45, 'mid': 50, 'final': 55}}, 'class_CNC': {'name': 'CNC', 'marks': {'quiz1': 42, 'quiz2': 44, 'mid': 53, 'final': 59}}}

student :  1 {'name': 'ali', 'class_AI': {'name': 'AI', 'marks': {'quiz1': 41, 'quiz2': 48, 'mid': 77, 'final': 55}}, 'class_CNC': {'name': 'CNC', 'marks': {'quiz1': 49, 'quiz2': 44, 'mid': 51, 'final': 56}}}

student :  2 {'name': 'raza', 'class_AI': {'name': 'AI', 'marks': {'quiz1': 51, 'quiz2': 10, 'mid': 12, 'final': 33}}, 'class_CNC': {'name': 'CNC', 'marks': {'quiz1': 33, 'quiz2': 99, 'mid': 100, 'final': 88}}}

student :  3 {'name': 'hassan', 'class_AI': {'name': 'AI', 'marks': {'quiz1': 41, 'quiz2': 66, 'mid': 67, 'final': 35}}, 'class_CNC': {'name': 'CNC', 'marks': {'quiz1': 40, 'quiz2': 5, 'mid': 68, 'final': 77}}}

student :  4 {'name': 'faizan', 'class_AI': {'name': 'AI', 'marks': {'quiz1': 41, 'quiz2': 48, 'mid': 50, 'final': 52}}, 'class_CNC': {'name': 'CNC', 'marks': {'quiz1': 40, 'quiz2': 60, 'mid': 76, 'final': 55}}}

student :  5 {'name': 'zehra', 'class_AI': {'name': 'AI', 'marks': {'quiz1': 41, 'quiz2': 78, 'mid': 65, 'final': 69}}, 'class_CNC': {'name': 'CNC', 'marks': {'quiz1': 75, 'quiz2': 74, 'mid': 73, 'final': 77}}}

student :  6 {'name': 'yawar', 'class_AI': {'name': 'AI', 'marks': {'quiz1': 99, 'quiz2': 88, 'mid': 60, 'final': 51}}, 'class_CNC': {'name': 'CNC', 'marks': {'quiz1': 51, 'quiz2': 53, 'mid': 44, 'final': 42}}}

student :  7 {'name': 'zakir', 'class_AI': {'name': 'AI', 'marks': {'quiz1': 39, 'quiz2': 84, 'mid': 89, 'final': 23}}, 'class_CNC': {'name': 'CNC', 'marks': {'quiz1': 46, 'quiz2': 47, 'mid': 98, 'final': 58}}}

student :  8 {'name': 'meesam', 'class_AI': {'name': 'AI', 'marks': {'quiz1': 48, 'quiz2': 89, 'mid': 97, 'final': 10}}, 'class_CNC': {'name': 'CNC', 'marks': {'quiz1': 90, 'quiz2': 25, 'mid': 20, 'final': 30}}}

In [20]:
name_list=[]
for i,student in enumerate(students):
    name_list.append(students[i]["name"])

    
print(name_list)

['arif', 'ali', 'raza', 'hassan', 'faizan', 'zehra', 'yawar', 'zakir', 'meesam']

In [21]:
print(name_list) 
student_name=input("\nEnter the student name you want to check result : ")
 
for i,student in enumerate(students):
    if student_name == students[i]["name"]:
        class1=max(students[i]["class_AI"]["marks"].values())
        class2=max(students[i]["class_CNC"]["marks"].values())
        finalresult=max(class1,class2)
        print("The max marks in class_AI is : " ,class1)
        print("The max marks in class_CNC  is : " ,class2)
        print("The best marks ",student_name," get is : " , finalresult)
        break

['arif', 'ali', 'raza', 'hassan', 'faizan', 'zehra', 'yawar', 'zakir', 'meesam']

Enter the student name you want to check result : zehra
The max marks in class_AI is :  78
The max marks in class_CNC  is :  77
The best marks  zehra  get is :  78